services:

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.25.8
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb-data:/pb_data
      - ./pb-hooks:/pb_hooks
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    # environment:
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    # command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
